config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :posts

  get '/todo', to: 'backbone#index', as: 'todo'
end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  has_many :checklist_items, dependent: :destroy
end

app/models/checklist_item.rb
class ChecklistItem < ActiveRecord::Base
  belongs_to :checklist
end

app/models/lead.rb
class Lead < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/leads_controller.rb
class Api::V1::LeadsController < ApplicationController
  respond_to :json

  def index
    respond_with Lead.all
  end

  def show
    respond_with lead
  end

  def create
    respond_with :api, :v1, Lead.create(lead_params)
  end

  def update
    respond_with lead.update(lead_params)
  end

  def destroy
    respond_with lead.destroy
  end

  private
  def lead
    Lead.find(params[:id])
  end

  def lead_params
    params.require(:lead).permit(:first_name, :last_name, :email, :phone, :status, :notes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backbone_controller.rb
class BackboneController < ApplicationController
  before_filter :authenticate_user!, only: :index

  def index
    render text: nil, layout: 'backbone'
  end
end

app/controllers/checklist_items_controller.rb
class ChecklistItemsController < ApplicationController
  before_action :set_checklist_item, only: [:show, :edit, :update, :destroy]
  before_action :set_checklist

  # GET /checklist_items/new
  def new
    @checklist_item = ChecklistItem.new(checklist_id: params[:checklist_id])
  end

  # GET /checklist_items/1/edit
  def edit
  end

  # POST /checklist_items
  def create
    @checklist_item = ChecklistItem.new(checklist_item_params)

    if @checklist_item.save
      redirect_to checklist_path(@checklist), notice: 'Checklist item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /checklist_items/1
  def update
    if @checklist_item.update(checklist_item_params)
      redirect_to @checklist_item, notice: 'Checklist item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /checklist_items/1
  def destroy
    @checklist_item.destroy
      redirect_to checklist_items_url, notice: 'Checklist item was successfully destroyed.'
  end

  private
    def set_checklist_item
      @checklist_item = ChecklistItem.find(params[:id])
    end

    def set_checklist
      @checklist = Checklist.find(params[:checklist_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checklist_item_params
      params[:checklist_item].permit([:description, :priority, :completed?])
    end
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  def index
    @checklists = Checklist.all
  end

  def show
    @checklist = Checklist.find(params[:id])
  end

  def new
    @checklist = Checklist.new
  end

  def create
    @checklist = Checklist.new(checklist_params)

    if @checklist.save
      redirect_to checklists_path, notice: 'Checklist was successfully created.'
    else
      render :new
    end
  end

  private
  def checklist_params
    params[:checklist].permit(:name)
  end
end

app/controllers/ember_controller.rb
class EmberController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find params[:id]
  end

  def edit
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    authorize @post, :manage?

    if @post.save
      flash[:success] = 'Post created!'
      redirect_to post_path(@post)
    else
      render action: new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :commit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    flash_type = flash_type.to_sym
    known_classes = {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }
    known_classes[flash_type] || flash_type.to_s
  end
end

app/helpers/checklist_helper.rb
module ChecklistHelper
end

app/helpers/checklist_items_helper.rb
module ChecklistItemsHelper
end

app/views/checklist_items/_form.html.haml
= form_for([@checklist, @checklist_item]) do |f|
  - if @checklist_item.errors.any?
    #error_explanation
      %h2
        = pluralize(@checklist_item.errors.count, "error")
        prohibited this checklist_item from being saved:

      %ul
      - @checklist_item.errors.full_messages.each do |message|
        %li
          = message

  .attributes
    = f.hidden_field :checklist_id
    %p
      = f.label :description
      = f.text_field :description
    %p
      = f.label :priority
      = f.number_field :priority

    %p
      = f.label :completed?
      = f.check_box :completed?
  .actions
    = f.submit

app/views/checklist_items/edit.html.haml
%h1
  Editing checklist_item

= render 'form'

= link_to 'Back', checklist_path(@checklist_item.checklist_id)

app/views/checklist_items/new.html.haml
%h1
  New checklist item:

= render 'form'

= link_to 'Back', checklist_path(@checklist)

app/views/checklists/_form.html.haml
= form_for(@checklist) do |f|
  - if @checklist.errors.any?
    #error_explanation
      %h2
        = pluralize(@checklist.errors.count, "error")
        prohibited this checklist from being saved:

      %ul
      - @checklist.errors.full_messages.each do |message|
        %li
          = message

  .attributes
    %p
      = f.label :name
      = f.text_field :name
  .actions
    = f.submit

app/views/checklists/index.html.haml
%h1
  Checklists
- @checklists.each do |checklist|
  %h3
    = link_to checklist.name, checklist_path(checklist)
%br
= link_to 'Add new checklist', new_checklist_path

app/views/checklists/new.html.haml
%h1
  New checklist

= render 'form'

= link_to 'Back', checklists_path

app/views/checklists/show.html.haml
%h1
  = @checklist.name

%table
  %thead
    %tr
      %th{ colspan:"3"}

  %tbody
    - @checklist.checklist_items.each do |checklist_item|
      %tr
        %td
          = checklist_item.description
        %td
          = link_to 'Edit', edit_checklist_checklist_item_path(@checklist, checklist_item)
        %td
          = link_to 'Destroy', checklist_checklist_item_path(@checklist, checklist_item), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'Add item to list', new_checklist_checklist_item_path(@checklist)

app/views/home/index.html.haml
.home
  .row
    .jumbotron
      .row
        .col-md-2
        .col-md-2
          = image_tag "osu_headshot_crop.jpg", height: 175, width: 175, class: 'img-thumbnail'
        .col-md-8
          %h1
            Shaun Hardin
          %h4
            Software Developer, Ohio State Graduate, and other things I'm sure...

.row
  .well
    Welcome to my personal site! If you are looking for an explanation of what this site is meant to be, I have some bad news for you.
    Originally, this site was intended to be a custom blog app written in Rails as a way to transition from .NET into the Rails ecosystem.
    Since then, I fear it has become a bit of a landing ground for toying with clientside frameworks like Backbone and Ember,
    as well as just a general place for experimenting with new things. It may or may not still be used as a blog, but if it looks
    abandoned then it is likely that life got in the way. Getting a dog, getting engaged, and buying a house can do that to you, I suppose.

.row
  .panel.panel-default
    .panel-heading.panel-title
      About Me
    .panel-body
      A graduate of Ohio State with a degree in Computer Science and Engineering, I have been professionally developing software since 2012.
      I started out in the .NET world but have since jumped head first into Ruby on Rails since joining CoverMyMeds in 2014. It's been a fun
      transition and I enjoy learning new things about Rails every day.

- if policy(:post).manage?
  %hr
  %h4
    Hello, admin user!
    .admin
      = link_to "Create new post", new_post_path

app/views/layouts/_navigation_links.html.haml
%li
  = link_to 'All Posts', posts_path
- if user_signed_in?
  %li
    = link_to 'To Do', todo_path
  %li
    = link_to 'Log Out', destroy_user_session_path, method: :delete
- else
  %li
    = link_to 'Log In', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Shaun Hardin
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag('application')
  = csrf_meta_tags
  %body
    %header
      = render 'shared/header.html.haml'
    .container
      = render partial: "shared/flash_messages", flash: flash

      = yield
      #ember-app

app/views/layouts/backbone.html.haml
!!!
%html
  %head
    %title
      Slog
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'backbone_app'
  = csrf_meta_tags
  %body
    %header
      = render 'shared/header.html.haml'
    .container
      = render partial: "shared/flash_messages", flash: flash
      #content
        // this should be placed elsewhere
        %section#todoapp
          %header#header
            %h1 To Dos
            %input.form-control.input-large#new-todo{autofocus: "", placeholder: "What needs to be done?"}
          %section#main
            %span
              %input#toggle-all{type: "checkbox"}
              = label_tag 'toggle-all', 'Toggle all items'
            %ul#todo-list
          %footer#footer
        #info
          %p Double-click to edit a todo
        = yield

app/views/post/show.html.haml
= link_to "Posts Index", post_index_path
%h2
  = @post.title

.content
  = @post.content

app/views/posts/index.html.haml
%ul.posts
  - @posts.each do |post|
    %li.post
      %h4
        = link_to "#{post.title}", post_path(post)
      %p
        = truncate post.content, length: 200

app/views/posts/new.html.haml
%h2
  Create a new blog post

= form_for @post, url: {action: "create"} do |f|
  %p
    .title
      = f.label :title, "Title: "
      = f.text_field :title
  %p
    .content
      = f.label :content, "Content: "
      %br
      = f.text_area :content
  %p
    = f.submit "Create post"

app/views/posts/show.html.haml
= link_to "Posts Index", posts_path
%h2
  = @post.title

.content
  = @post.content

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div{:class => "alert #{bootstrap_class_for(type)} fade in"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-collapse")
        %span.sr-only
          Toggle navigation
        %span.icon-bar
      = link_to 'Shaun Hardin', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'